### PR TITLE
Remove node_modules + small changes

### PR DESCRIPTION
**Pull request by amanogawa01**

### CODE REVIEW

**Comment by ApocalypseCalculator** [comment]
uhhh whats this?

**Review by ApocalypseCalculator — CHANGES_REQUESTED** [review]
I don't see much of a point in the reformatting of the code. If anything, it is a bit of a nuisance.

**Comment by amanogawa01** [comment]
alright, do you just want the node modules removed then?

**Review by ApocalypseCalculator — COMMENTED** [review]
Thanks lol

**Review by ApocalypseCalculator — APPROVED** [review]

**Pull request merged**
